name: Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2

    - name: install gems
      run: bundle install
    
    - name: Setup JVM
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
            
    - name: Download FHIR validator
      run: wget -q https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar -O validator.jar
    
    - name: Run au-patient tests
      run: bundle exec cucumber --color --quiet features/profiles/AUBasePatient 
